// Generated by Selenium IDE


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.fail;


public class SearchExportedFromIDETest {
  private WebDriver driver;
  private String baseUrl="";
  private StringBuffer verificationErrors = new StringBuffer();
  @BeforeEach
  public void setUp() throws Exception {
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @Test
  public void testSearchExportedFromIDE() throws Exception {
    driver.get("/");
    driver.findElement(By.id("sted")).clear();
    driver.findElement(By.id("sted")).sendKeys("Stockholm");
    driver.findElement(By.id("queryknapp")).click();
    driver.findElement(By.xpath("//div[@id='directories']/table/tbody/tr/td[2]/a")).click();
    driver.findElement(By.cssSelector("li")).click();
    Assertions.assertEquals("Weather forecast forStockholm (Sweden)", driver.findElement(By.cssSelector("h1")).getText());
  }

  @AfterEach
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }
}
